name: ci/gh-actions/verify-merge

on: [push, pull_request]

jobs:
  verify-merge:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: verify-merge
      run: python3 ./verify-merge.py --import-keys

